apiVersion: v1
kind: Service
metadata:
  name: go-client
  labels:
    app: go-client
    service: go-client
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: go-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-client-v1
  labels:
    app: go-client
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-client
      version: v1
  template:
    metadata:
      labels:
        app: go-client
        version: v1
    spec:
      containers:
      - name: go-client
        image: spider/client
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
